### ISSUE TITLE
ルートフォルダの扱いについて

### ISSUE THREAD

**Issue by Necnion8** [Necnion8/CraftSwitcher-2#6]
#### A. ルートを決めたらSwitcher側が鯖フォルダを自動で管理 (CraftyControllerなど)
- サーバーフォルダを意識することなく、勝手に作成したり削除したりできる。

#### B. ルート内なら自由に鯖フォルダを選択できる (CraftSwitcherV1)
- CraftSwitcherの管理下にサーバーを置かなくても良い。移動や手動で管理しやすい。

<br>
どちらにも対応したいがどうしよう。

**Comment by Necnion8** [comment]
A で使えるようにします。
UIからの操作でサーバーを作成する時は、設定されたサーバー保管場所を使うようにしつつ
CraftSwitcherのサーバーリストに手動で外部のパスを加えても管理できるようにしてしまおう

**Comment by Necnion8** [comment]
eg.
```yml
# ルートとして扱うシステム上のディレクトリパス
root_directory: "/opt/minecraft"

# サーバーを保管するフォルダ
servers_location: "/servers"  # 実際のパス: /opt/minecraft/servers
```
